# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB"
    chainName: source
    connections:
      - token: ethereum|destination|0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB
    decimals: 18
    name: Espresso Composables WETH
    standard: EvmHypSynthetic
    symbol: ECWETH
  - addressOrDenom: "0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB"
    chainName: destination
    connections:
      - token: ethereum|source|0x84eA74d481Ee0A5332c457a4d796187F6Ba67fEB
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ECWETH
